// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVV5ejY40vCCvFwZDyrYlv7NbQx8sPCo',
    appId: '1:212823823056:android:5c2a776606299322b244d5',
    messagingSenderId: '212823823056',
    projectId: 'flutter-instagram-clone-4df97',
    storageBucket: 'flutter-instagram-clone-4df97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByHW4iVFG0y8wXKQIx-mN3bjRwMi-vg38',
    appId: '1:212823823056:ios:1982f66b4f288ae6b244d5',
    messagingSenderId: '212823823056',
    projectId: 'flutter-instagram-clone-4df97',
    storageBucket: 'flutter-instagram-clone-4df97.firebasestorage.app',
    iosClientId: '212823823056-sumaasulunke0kks93492rn99tkq6rj7.apps.googleusercontent.com',
    iosBundleId: 'com.stevenitch.flutterInstagramClone',
  );
}
