// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAKNzp3EXK6Ddonb6mzxOg3uwUwu9KEY4',
    appId: '1:928143527564:android:060448fd3a07985ca6f5a9',
    messagingSenderId: '928143527564',
    projectId: 'flutter-instagram-clone-6aa49',
    storageBucket: 'flutter-instagram-clone-6aa49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWWezbSxxWlT2SEgmCvrnWlxiRqEPKmJA',
    appId: '1:928143527564:ios:42fc3b84f57e51e8a6f5a9',
    messagingSenderId: '928143527564',
    projectId: 'flutter-instagram-clone-6aa49',
    storageBucket: 'flutter-instagram-clone-6aa49.firebasestorage.app',
    iosClientId: '928143527564-a8sm9scbjuir5aehdbk7atksgtsrhbd7.apps.googleusercontent.com',
    iosBundleId: 'com.stevenitch.flutterInstagramClone.stg',
  );
}
